export default [
  "b--dotted",
  "b--dashed",
  "b--solid",
  "b--none",
  "b--dotted-ns",
  "b--dashed-ns",
  "b--solid-ns",
  "b--none-ns",
  "b--dotted-m",
  "b--dashed-m",
  "b--solid-m",
  "b--none-m",
  "b--dotted-l",
  "b--dashed-l",
  "b--solid-l",
  "b--none-l",
];
