export default [
  "nested-copy-line-height p",
  "nested-copy-line-height ul",
  "nested-copy-line-height ol",
  "nested-headline-line-height h1",
  "nested-headline-line-height h2",
  "nested-headline-line-height h3",
  "nested-headline-line-height h4",
  "nested-headline-line-height h5",
  "nested-headline-line-height h6",
  "nested-list-reset ul",
  "nested-list-reset ol",
  "nested-copy-indent p+p",
  "nested-copy-seperator p+p",
  "nested-img img",
  "nested-links a",
];
